USE universityBranch;

CREATE TABLE Students(
    SID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    SEMESTER INT NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    AVAILCOURSES INT NOT NULL,
    ENROLLMENTYEAR INT NOT NULL,
    PRIMARY KEY(SID)
);

CREATE TABLE Teachers(
    TID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    PRIMARY KEY(TID)
);

CREATE TABLE Courses(
    CID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SEMESTER INT,
    TID INT,
    PRIMARY KEY(CID),
    FOREIGN KEY(TID) REFERENCES Teachers(TID)
);

CREATE TABLE Attends(
    SID INT NOT NULL,
    CID INT NOT NULL,
    GRADE FLOAT,
    PRIMARY KEY(SID,CID),
    FOREIGN KEY(SID) REFERENCES Students(SID),
    FOREIGN KEY(CID) REFERENCES Courses(CID)
);

INSERT INTO Students(NAME,SURNAME,SEMESTER,PASSWORD,AVAILCOURSES,ENROLLMENTYEAR)
VALUES("Michael","Ieronymidis",6,"$2a$10$bFMlJIrRPGPFi5npbHX6wuVg9Ip8L47aU4qYoXHxR0NA9O6bBUVFC",7,2022);

INSERT INTO Teachers(NAME,SURNAME,PASSWORD)
VALUES("Panagiwths","Giannakopoulos","$2a$10$RWRJZLiRM5SggVOfGG0RHuKaNh5JM7lpBkaCnqc0TwLCA5W57jkT2"),
("Stavros","Fatouros","$2a$10$E5ui4CFR4pSk2wcD2Yjav.dalGgc7Vw7o6.KRrFX.O9Tt32GBgMO.");

INSERT INTO Courses(NAME,SEMESTER,TID)
VALUES("Microelectronics",6,1),("Electronics",6,2);

INSERT INTO Attends(SID,CID,GRADE)
VALUES(1,1,NULL);
