USE universityBranch;

CREATE TABLE Students(
    SID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    SEMESTER INT NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    AVAILCOURSES INT NOT NULL,
    PRIMARY KEY(SID)
);

CREATE TABLE Teachers(
    TID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    PRIMARY KEY(TID)
);

CREATE TABLE Courses(
    CID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SEMESTER INT,
    TID INT NOT NULL,
    PRIMARY KEY(CID),
    FOREIGN KEY(TID) REFERENCES Teachers(TID)
);

CREATE TABLE Attends(
    SID INT NOT NULL,
    CID INT NOT NULL,
    GRADE FLOAT,
    PRIMARY KEY(SID,CID),
    FOREIGN KEY(SID) REFERENCES Students(SID),
    FOREIGN KEY(CID) REFERENCES Courses(CID)
);

INSERT INTO Students(NAME,SURNAME,SEMESTER,PASSWORD,AVAILCOURSES)
VALUES("Michael","Ieronymidis",6,"hello",7);

INSERT INTO Teachers(NAME,SURNAME,PASSWORD)
VALUES("Panagiwths","Giannakopoulos","russia"),
("Stavros","Fatouros","uniwa");

INSERT INTO Courses(NAME,SEMESTER,TID)
VALUES("Microelectronics",6,1),("Electronics",6,2);

INSERT INTO Attends(SID,CID,GRADE)
VALUES(1,1,NULL);
